# code: language=Ansible insertSpaces=true tabSize=2

- name: Set custom facts
  set_fact:
    system_ansible_pip: "python{{ ansible_python.version.major }}-pip"
  tags: [always]


- name: Setup Ansible user account
  user:
    name: "{{ system_ansible_user_name }}"
    comment: "{{ system_ansible_user_comment }}"
    state: present
    password_lock: yes
  tags: [never, setup]


- name: Update packages list
  apt:
    update_cache: yes
  register: _apt_update
  until: not _apt_update.failed
  retries: 10
  delay: 10
  tags: [never, setup]


- include_tasks:
    file: "{{ item }}"
  loop:
    - services/ssh.yml
    - services/sudo.yml
    - services/pip.yml
  tags: [always]
