# code: language=Ansible insertSpaces=true tabSize=2

- name: Install PIP
  package:
    name: "{{ system_ansible_pip }}"
  register: _install_pip
  until: not _install_pip.failed
  retries: 10
  delay: 10
  tags: [never, setup]
