# code: language=Ansible insertSpaces=true tabSize=2

- name: Install Ansible user public key (from file)
  authorized_key:
    user: "{{ system_ansible_user_name }}"
    key: "{{ lookup('file', system_ansible_public_key_file) }}"
    state: present
  when:
    - system_ansible_public_key_file is defined and system_ansible_public_key_file | length > 0
  tags: [never, setup]


- name: Install Ansible user public key (from variable)
  authorized_key:
    user: "{{ system_ansible_user_name }}"
    key: "{{ system_ansible_public_key }}"
    state: present
  when:
    - system_ansible_public_key is defined and system_ansible_public_key | length > 0
  tags: [never, setup]

# ---

- name: Remove Ansible user public key (from file)
  authorized_key:
    user: "{{ system_ansible_user_name }}"
    key: "{{ lookup('file', system_ansible_public_key_file) }}"
    state: absent
  when:
    - system_ansible_public_key_file is defined and system_ansible_public_key_file | length > 0
  tags: [never, teardown, remove]


- name: Remove Ansible user public key (from variable)
  authorized_key:
    user: "{{ system_ansible_user_name }}"
    key: "{{ system_ansible_public_key }}"
    state: absent
  when:
    - system_ansible_public_key is defined and system_ansible_public_key | length > 0
  tags: [never, teardown, remove]
