# code: language=Ansible insertSpaces=true tabSize=2

- name: Install sudo
  package:
    name: sudo
    state: present
  register: _install_sudo
  until: not _install_sudo.failed
  retries: 10
  delay: 10
  tags: [never, setup]


- name: Install sudo configuration
  template:
    src: sudoers.j2
    dest: "{{ system_ansible_sudoers_file }}"
  tags: [never, setup]


- name: Remove sudo configuration
  file:
    path: "{{ system_ansible_sudoers_file }}"
    state: absent
  tags: [never, teardown, remove]
